### PR TITLE
Create index_new.html

### PR DESCRIPTION
**Pull request by natesheehan**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
OK but we want something in index.html, more than 10 lines, no? 

image

**Comment by eugenividal** [comment]
Wow, looking great!

**Comment by natesheehan** [comment]
> OK but we want something in index.html, more than 10 lines, no?
> 
> image

Shouldn't be 10, I am seeing a normal amount ->
Screenshot from 2022-08-03 11-41-58

**Comment by natesheehan** [comment]
The deploy link is a little out of sync, but I have just pushed a change to make the map full screen instead of a little square.

**Comment by Robinlovelace** [comment]
Aha yes OK I think it's just 10 lines that have changed. Looking good.

**Comment by Robinlovelace** [comment]
Looking great, improvement 4 sure so merging 

image

**Comment by Robinlovelace** [comment]
any ideas whats going on with the counties? seems not all boundaries are there..

**Pull request merged**
